### ISSUE TITLE
Implement text item

### ISSUE THREAD

**Issue by TortoiseWrath** [multacc/multacc#100]
just displays some fuckin text

**Comment by mayank99** [comment]
y tho 🤔

**Comment by TortoiseWrath** [comment]
wOuLd iT mAkE sEnSe tO bAsE oThEr iTemS oN toP oF tHiS SiNcE a LoT oF iTeMs WouLd pRoBabLy jUsT bE tExT?

**Comment by TortoiseWrath** [comment]
because we can :exceptionallyfastparrot:

**Comment by mayank99** [comment]
Well, everything is text so this should be a generic MultaccItem

**Comment by TortoiseWrath** [comment]
MultaccItem is abstract
