### ISSUE TITLE
Ensure font used to display items has tabular numerals

### ISSUE THREAD

**Issue by TortoiseWrath** [multacc/multacc#19]
This will make phone numbers line up with each other. This should be done once the frontend design is complete.

**Comment by mayank99** [comment]
See #23. Open sans is the text theme used for non-header text.
([main.dart:42](https://github.com/multacc/multacc/pull/23/files#diff-fe53fad46868a294b309fc85ed138997R42))

**Comment by TortoiseWrath** [comment]
looks good; will reopen this issue if it becomes ugly again in the future
