### ISSUE TITLE
Fix google sign in

### ISSUE THREAD

**Issue by mayank99** [multacc/multacc#235]
Needs to be fixed completely for once.

Right now signing in with a google account works fine on my device when I run from the IDE, but if I try the release version from Play Store beta, it fails.

~~That's because app signing was never configured for the release version.~~

https://github.com/multacc/multacc/blob/d2240123e82c3d7d2c8da47f1a9207da4214c37c/android/app/build.gradle#L51-L52

**Comment by mayank99** [comment]
The firebase console now has new release fingerprints from the Google Play Console. So `google-services.json` has been updated.

**Comment by mayank99** [comment]
Reopening because this could take a couple months to actually work.
![image](https://user-images.githubusercontent.com/9084735/80927814-00556b00-8d66-11ea-95f1-0295f9045ec8.png)

**Comment by TortoiseWrath** [comment]
> Because you updated the application logo, your app registration requires verification by Google.

how is this a cause and effect relationship

**Comment by mayank99** [comment]
It doesn't have to make sense. If Google thinks it's cause-and-effect, it is.

**Comment by mayank99** [comment]
Closing again because it's fixed magically.
