### ISSUE TITLE
Implement Profile screen

### ISSUE THREAD

**Issue by mayank99** [multacc/multacc#25]

**Comment by TortoiseWrath** [comment]
Profile should be a MultaccContact. This helps with #68 as well since we already have a way to store those.

**Comment by mayank99** [comment]
I was assuming there is going to be a lot more information stored in a profile, such as auth tokens

**Comment by TortoiseWrath** [comment]
profile != user settings

profile is the stuff you can share, I thought

**Comment by mayank99** [comment]
Profile is stuff that's stored. You create MultaccContact from a profile for sharing. So if a user has multiple templates saved, those would be MultaccContacts but the overall profile should be its own type

**Comment by TortoiseWrath** [comment]
Making the "profile" just be the user's complete MultaccContact makes implementation easier since this makes the profile screen the same as the edit contact screen (they would have the same UX anyway). The saved templates should not include the whole contact information for those templates but just the information required to generate a subset MultaccContact from the base profile MultaccContact. 

It is no problem for the information that is not shared (auth tokens, user preferences, etc) to not be part of the profile object. In fact, it shouldn't be since it is a different type of information. It will all go in the settings hive box alongside the profile.

**Comment by TortoiseWrath** [comment]
and users should be able to back up their profile (shareable information) but not their app settings and vice versa

**Comment by TortoiseWrath** [comment]
so user settings include:
* MultaccContact profile
* List<MultaccTemplate> templates
* boolean darkMode
* String groupmeToken
* boolean backupSettings
* boolean backupProfile
etc etc

everything is way cleaner this way

**Comment by TortoiseWrath** [comment]
having a separate way (besides MultaccContact) to store contact information in the profile vs the contacts is pointless

**Comment by mayank99** [comment]
> Making the "profile" just be the user's complete MultaccContact makes implementation easier since this makes the profile screen the same as the edit contact screen (they would have the same UX anyway).

> having a separate way besides MultaccContact to store contact information in the profile vs the contacts is pointless

Hard disagree with both points. Profile and Contact have some similarities but the two are very different in terms of UX and logic

**Comment by TortoiseWrath** [comment]
Hard disagree. There's no reason they should be. In both cases you're editing a name, an avatar, a birthday, and a set of MultaccItems.

**Comment by TortoiseWrath** [comment]
They are literally the same thing

**Comment by TortoiseWrath** [comment]
And users will expect the same UX for editing their own contact info vs  someone else's

**Comment by TortoiseWrath** [comment]
this is the first time I actually cannot comprehend where you are coming from

**Comment by mayank99** [comment]
Editing is more similar, but the Adding/Viewing flow is very different. Your profile is built part by part, based on shit you add, whereas a Contact is just saved fully. When viewing, you don't need to message and call yourself or even view your instagram profile, for example.

**Comment by TortoiseWrath** [comment]
Yes, displaying the contact is different but editing it is exactly the same

**Comment by TortoiseWrath** [comment]
Nothing I am saying contradicts this. I am saying they are the same type of data and there's no reason not to use the same class to store said data

**Comment by TortoiseWrath** [comment]
> Your profile is built part by part, based on shit you add, whereas a Contact is just saved fully. 

What fucking difference does it make? In either case you can open the contact, add something, save the contact, open it again, add some more things, save it, open it again, remove some things, etc etc

**Comment by TortoiseWrath** [comment]
And adding is just editing but starting with nothing

**Comment by TortoiseWrath** [comment]
![image](https://user-images.githubusercontent.com/13744174/76560784-ef782f80-646f-11ea-8096-75b9c9410673.png)
![image](https://user-images.githubusercontent.com/13744174/76560796-f43ce380-646f-11ea-9585-8cbffc6818d4.png)
![image](https://user-images.githubusercontent.com/13744174/76560807-f737d400-646f-11ea-96ac-21da048f1ad7.png)
Look at how they're the same, like they should be

**Comment by TortoiseWrath** [comment]
> ```class Settings {
  MultaccContact profile; // All my contact information. This is what I am editing when I edit my profile
  List&lt;MultaccTemplate&gt; template; // Templates I can use to remove some info from the profile. This is what I am editing when I edit my templates
  
  // Other shit
  String whateverKey;
  bool darkMode;
}

// somewhere else, like in the sharing screen class
share(MultaccContact profile, MultaccTemplate template) {
  MultaccContact contact = MultaccContact.createSubset(profile, template);
  // share the contact
}```
<sub>[View in Slack](https://cs495-group-workspace.slack.com/archives/CV2TA3AET/p1584043275042200)</sub>

**Comment by TortoiseWrath** [comment]
so uh anyway

the page to edit the profile is the same as the page to edit a contact

**Comment by TortoiseWrath** [comment]
Completion of the profile page is presumably blocked on #104

**Comment by TortoiseWrath** [comment]
Sharing is blocked on #154, profile storage is #68

**Comment by TortoiseWrath** [comment]
Share screen will have a lot going on besides the profile screen, which is largely the same as the add/edit screen from #104. Should these issues be reorganized?

**Comment by mayank99** [comment]
Sure. The only thing they really have in common is that share screen is accessed from the profile screen.

**Comment by mayank99** [comment]
No longer blocked after #170 but is now sort of blocking #165
