### ISSUE TITLE
The code currently in master does not build

### ISSUE THREAD

**Issue by TortoiseWrath** [multacc/multacc#30]
![image](https://user-images.githubusercontent.com/13744174/76136946-d9481a80-5ffc-11ea-8ec4-aaf9ab5dd1ac.png)
see line 7 in contacts_data.dart (displays error in Android Studio)

Appears related to #13 and its closing PR #23

**Comment by mayank99** [comment]
~~_Have you tried turning it off and on again?~~

Run `flutter packages pub run build_runner build -v` everytime the model changes. Or use a vscode plugin like flutter_mobx

**Comment by mayank99** [comment]
> ~Have you tried turning it off and on again?~

Run `flutter packages pub run build_runner build -v` everytime the model changes. Or use a vscode plugin like flutter_mobx
<sub>[View in Slack](https://cs495-group-workspace.slack.com/archives/CSD5JKT0F/p1583556952073000)</sub>
