### ISSUE TITLE
Store entire MultaccContact in local db

### ISSUE THREAD

**Issue by mayank99** [multacc/multacc#70]
Might need to change the class structure or might just need the custom hive adapter

**Comment by TortoiseWrath** [comment]
do you want to do this or do you want me to do this

**Comment by mayank99** [comment]
> yes
<sub>[View in Slack](https://cs495-group-workspace.slack.com/archives/CV2TA3AET/p1583990477025700)</sub>

**Comment by mayank99** [comment]
@TortoiseWrath If you do this, I'll take care of #16

**Comment by TortoiseWrath** [comment]
lol ok
