### ISSUE TITLE
Implement website/URL item

### ISSUE THREAD

**Issue by TortoiseWrath** [multacc/multacc#99]
So users can add generic links to their profile

**Comment by mayank99** [comment]
😮
My website rhymes with kornhub.com

**Comment by mayank99** [comment]
Would it make sense to base other items on top of this since a lot of profiles would probably just be URLs?

**Comment by TortoiseWrath** [comment]
eh not really, the only thing that would be constant between them is the value format and launchApp, which are both trivial so idk if it makes much difference
